name: Releasing APK files
description: "a"
inputs:
  release_name:
    required: true
runs:
  using: "composite"
  steps:
    - name: Generate release info
      shell: bash
      run: |
        echo  -e "
        **This repository is not like any other repository. It does not create new releases; it only releases new files.**
        \n ## Click the first APK for the latest \n The first version in app version, second is patch(if applicable) "> ${{ github.workspace }}-CHANGELOG.txt
    - name: Release
      uses: ncipollo/release-action@v1.21.0
      with:
        artifacts: |
          ./release/*.apk
        name: "Get APKs"
        tag: "all"
        bodyFile: ${{ github.workspace }}-CHANGELOG.txt
        allowUpdates: tru
