name: Manual Patch
permissions: write-all
env:
  repository: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  org_input: ${{ inputs.org }}
  org_event_input: ${{ github.event.inputs.org }}
on:
  workflow_dispatch:
    inputs:
      org:
        description: 'Which apps do you want to patch?'
        required: true
        default: 'All'
        type: choice
        options:
          - 'All'
          - 'Morphe YouTube'
          - 'piko X'
          - 'piko Instagram'
          - 'hoo-dles Proton VPN'
          - 'hoo-dles Prime Video'
          - 'binarymend Symfonium'
          - 'Revenge Discord'
  workflow_call:
    inputs:
      org:
        required: true
        type: string
jobs:
  patch_morphe:
    name: Patch Morphe (YouTuhe)
    if: ${{ github.event.inputs.org == 'Morphe YouTube' || inputs.org == 'Morphe YouTube' || inputs.org == 'all' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > ks.keystore
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 --decode > ks-p12.keystore
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh
        run: bash src/etc/connection.sh
      - name: Patch apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
        id: patch
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/build/build.sh "morphe-youtube"
      - name: Releasing APK files
        id: release
        if: steps.check-gh.outputs.internet_error == '0'
        uses: ./.github/actions/release
  patch_piko_twitter:
    name: Patch Piko (X)
    if: ${{ github.event.inputs.org == 'piko X' || inputs.org == 'piko X' || inputs.org == 'all' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > ks.keystore
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 --decode > ks-p12.keystore
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh
        run: bash src/etc/connection.sh
      - name: Patch apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
        id: patch
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/build/build.sh "piko-x"
      - name: Releasing APK files
        id: release
        if: steps.check-gh.outputs.internet_error == '0'
        uses: ./.github/actions/release
  patch_piko_instagram:
    name: Patch Piko (Instagram)
    if: ${{ github.event.inputs.org == 'piko Instagram' || inputs.org == 'piko Instagram' || inputs.org == 'all' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > ks.keystore
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 --decode > ks-p12.keystore

      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/build/build.sh "piko-instagram"
      - name: Releasing APK files
        id: release
        if: steps.check-gh.outputs.internet_error == '0'
        uses: ./.github/actions/release
      
  patch_hoo-dles_protonvpn:
    name: Patch hoo-dles(ProtonVPN)
    if: ${{ github.event.inputs.org == 'hoo-dles Proton VPN' || inputs.org == 'hoo-dles Proton VPN' || inputs.org == 'all' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > ks.keystore
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 --decode > ks-p12.keystore

      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/build/build.sh "hoo-dles-protonvpn"
      - name: Releasing APK files
        id: release
        if: steps.check-gh.outputs.internet_error == '0'
        uses: ./.github/actions/release

  patch_hoo-dles_prime-video:
    name: Patch hoo-dles(Prime Video)
    if: ${{ github.event.inputs.org == 'hoo-dles Prime Video' || inputs.org == 'hoo-dles Prime Video' || inputs.org == 'all' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > ks.keystore
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 --decode > ks-p12.keystore

      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
        if: steps.check-gh.outputs.internet_error == '0'
        run: | 
         bash src/build/build.sh "hoo-dles-prime-video"
      - name: Releasing APK files
        id: release
        if: steps.check-gh.outputs.internet_error == '0'
        uses: ./.github/actions/release

  patch_binarymend_symfonium:
    name: Patch binarymend(Symfonium)
    if: ${{ github.event.inputs.org == 'binarymend Symfonium' || inputs.org == 'binarymend Symfonium' || inputs.org == 'all' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > ks.keystore
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 --decode > ks-p12.keystore

      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
        if: steps.check-gh.outputs.internet_error == '0'
        run: | 
          bash src/build/build.sh "binarymend-sympfonium"
      - name: Releasing APK files
        id: release
        if: steps.check-gh.outputs.internet_error == '0'
        uses: ./.github/actions/release

  patch_revenge_discord:
    name: Patch Revenge Discord
    if: ${{ github.event.inputs.org == 'Revenge Discord' || inputs.org == 'Revenge Discord' || inputs.org == 'all' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > ks.keystore
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 --decode > ks-p12.keystore

      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
        if: steps.check-gh.outputs.internet_error == '0'
        run: | 
         bash src/build/build.sh "revenge-discord"
      - name: Releasing APK files
        id: release
        if: steps.check-gh.outputs.internet_error == '0'
        uses: ./.github/actions/release
