name: 1. Manual Patch
permissions: write-all
env:
  repository: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  org_input: ${{ inputs.org }}
  org_event_input: ${{ github.event.inputs.org }}
on:
  workflow_dispatch:
    inputs:
      org:
        description: 'Which "Morphe" patches do you want to patch?'
        required: true
        default: 'Morphe'
        type: choice
        options:
          - 'Morphe YouTube'
          - 'piko X'
          - 'piko Instagram'
          - 'hoo-dles Prime Video'
          - 'All'
  workflow_call:
    inputs:
      org:
        required: true
        type: string
jobs:
  patch_morphe:
    name: Patch Morphe (YouTuhe)
    if: ${{ github.event.inputs.org == 'Morphe YouTube' || inputs.org == 'Morphe YouTube' || inputs.org == 'all' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-morphe
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-morphe
        if: steps.check-gh-morphe.outputs.internet_error == '0'
        run: bash src/build/build.sh "morphe-patches" "MorpheApp" "com.google.android.youtube" "youtube" "google-inc/youtube/youtube" 
      - name: Releasing APK files
        id: releasemorphe
        if: steps.check-gh-morphe.outputs.internet_error == '0'
        uses: ./.github/actions/release
        with:
         release_name: "YouTube Morphe"
  patch_piko_twitter:
    name: Patch Piko (X)
    if: ${{ github.event.inputs.org == 'piko X' || inputs.org == 'piko X' || inputs.org == 'all' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-morphe
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-morphe
        if: steps.check-gh-morphe.outputs.internet_error == '0'
        run: bash src/build/build.sh "piko" "crimera" "com.twitter.android" "X" "x-corp/twitter/x" "Bundle_extract"
      - name: Releasing APK files
        id: releasemorphe
        if: steps.check-gh-morphe.outputs.internet_error == '0'
        uses: ./.github/actions/release
        with:
         release_name: "X piko"
  patch_piko_instagram:
    name: Patch Piko (Instagram)
    if: ${{ github.event.inputs.org == 'piko Instagram' || inputs.org == 'piko Instagram' || inputs.org == 'all' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-morphe
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-morphe
        if: steps.check-gh-morphe.outputs.internet_error == '0'
        run: bash src/build/build.sh "piko" "crimera" "com.instagram.android" "instagram-arm64-v8a" "instagram-android/com.instagram.android" "apkpure" "Bundle_extract"
      - name: Releasing APK files
        id: releasemorphe
        if: steps.check-gh-morphe.outputs.internet_error == '0'
        uses: ./.github/actions/release
        with:
         release_name: "Instagram piko"
  patch_hoo-dles-primevideo:
    name: Patch hoo-dles (Prime Video)
    if: ${{ github.event.inputs.org == 'hoo-dles Prime Video' || inputs.org == 'hoo-dles Prime Video' || inputs.org == 'all' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Check github connection
        id: check-gh-morphe
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-morphe
        if: steps.check-gh-morphe.outputs.internet_error == '0'
        run: bash src/build/build.sh "morphe-patches" "hoo-dles" "com.amazon.avod.thirdpartyclient" "amazon-prime-video" "amazon-mobile-llc/amazon-prime-video/amazon-prime-video" "arm64-v8a"
      - name: Releasing APK files
        id: releasemorphe
        if: steps.check-gh-morphe.outputs.internet_error == '0'
        uses: ./.github/actions/release
        with:
         release_name: "hoo-dles Prime Video"
      
