name: Xposed Patches
permissions: write-all
on:
  schedule:
    - cron: "0 0/4 * * *"
  workflow_dispatch:

jobs:
  Patch-Revenge-Discord:
    name: Patch Revenge(Discord)
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Revenge Discord"
    secrets: inherit

