name: Patch APKs (LSPatch)
on:
  workflow_call:
    inputs:
      from_ci:
        type: boolean
        required: false
        default: true

  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  Revenge:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > sign.keystore
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 --decode > ks-p12.keystore
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
      - name: Get Files
        run: |
          export mver="$(curl -fL https://api.github.com/repos/revenge-mod/revenge-xposed/releases/latest  | jq .name)"
          echo "[+] Downloading Revenge $mver"
          wget -q https://github.com/revenge-mod/revenge-xposed/releases/latest/download/app-release.apk
          echo '[+] Downloading APKEditor'
          wget -q $(curl -fSL https://api.github.com/repos/REAndroid/APKEditor/releases/latest | jq -r '.assets[0].browser_download_url') -O apkeditor.jar
          echo '[+] Downloading LSPatch'
          wget -q https://github.com/JingMatrix/LSPatch/releases/latest/download/lspatch.jar
          echo "[+] Downloadong Discord"
          export ver=$(curl https://tracker.vd.nexpid.xyz/tracker/index | jq .latest.beta)
          mkdir splits
          wget -q "https://tracker.vd.nexpid.xyz/tracker/download/$ver/config.arm64_v8a" -O splits/config.arm64_v8a.apk
          wget -q "https://tracker.vd.nexpid.xyz/tracker/download/$ver/config.x86_64" -O splits/config.x86_64.apk
          wget -q "https://tracker.vd.nexpid.xyz/tracker/download/$ver/config.en" -O splits/config.en.apk
          wget -q "https://tracker.vd.nexpid.xyz/tracker/download/$ver/config.xxhdpi" -O splits/config.xxhdpi.apk
          wget -q "https://tracker.vd.nexpid.xyz/tracker/download/$ver/base" -O splits/base.apk
          export aver="$(java -jar apkeditor info -i /sdcard/download/base.apk -version-name | cut -d'=' -f2-)"
          
          
          
          
          
      - name: Patch
        run: |
          java -jar apkeditor.jar m -i splits -o discord.apk
          java -jar lspatch.jar discord.apk -m app-release.apk -l 2 -o build -k ks-p12.keystore ${{ secrets.KEYSTORE_PASS }} ${{ secrets.KEYSTORE_ALIAS }} ${{ secrets.KEYSTORE_PASS }}
          echo "Discord: $aver Revenge: $pver" > build_log.txt
    
      - name: Release
        uses: ncipollo/release-action@v1.21.0
        with:
         artifacts: |
          ./build/*.apk
         name: Discord-Revenge
         tag: Discord-Revenge
         bodyFile: build_log.txt
         allowUpdates: true
