name: Patch APKs (LSPatch)
on:
  workflow_call:
    inputs:
      from_ci:
        type: boolean
        required: false
        default: true

  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  Revenge:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > sign.keystore
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 --decode > ks-p12.keystore
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY
          NEXT_VER_CODE: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
          
      - name: Get Files and Patch
        run: |
          export mver="$(curl -fL https://api.github.com/repos/revenge-mod/revenge-xposed/releases/latest  | jq .name)"
          export aver="$(curl https://apkcombo.com/discord/com.discord/download/apk | grep -oE '[0-9]+\.[0-9]+ - Stable' | sort -V | tail -n 1)"
          echo "[+] Downloading Revenge $mver"
          wget -q --header="Authorization: $GITHUB_TOKEN" https://github.com/revenge-mod/revenge-xposed/releases/latest/download/app-release.apk
          echo '[+] Downloading APKEditor'
          wget $(curl -fSL https://api.github.com/repos/REAndroid/APKEditor/releases/latest | jq -r '.assets[0].browser_download_url') -O apkeditor.jar
          echo '[+] Downloading LSPatch'
          wget -q https://github.com/JingMatrix/LSPatch/releases/latest/download/app-release.apk
          echo "[+] Downloadong Discord $aver"
          wget -q "https://apkcombo.com$(curl https://apkcombo.com/discord/com.discord/download/apk | grep -Po '(?<=href=["\"])(?!https?://)[^"\"]+' | grep r2)" -o discord.apk

    
      - name: Release
        uses: ncipollo/release-action@v1.21.0
        with:
         artifacts: |
          ./build/*.apk
         name: FCL-CoD
         tag: FCL-CoD
         bodyFile: build_log.txt
         allowUpdates: true
